# Generated by Django 5.1.7 on 2026-04-10 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='account_name',
            field=models.CharField(blank=True, help_text='Account holder name for the payout channel.', max_length=200),
        ),
        migrations.AlterField(
            model_name='payout',
            name='account_number',
            field=models.CharField(blank=True, help_text='GCash number / bank account number / Maya number.', max_length=100),
        ),
        migrations.AlterField(
            model_name='payout',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal admin notes (not visible to doctor).'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total payout amount requested (sum of doctor_earnings for included appointments).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payout',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name (only for bank_transfer method).', max_length=100),
        ),
        migrations.AlterField(
            model_name='payout',
            name='doctor',
            field=models.ForeignKey(help_text='The doctor requesting the payout.', limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payout',
            name='method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer'), ('maya', 'Maya'), ('other', 'Other')], default='gcash', help_text='Preferred payout channel.', max_length=20),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payout_reference',
            field=models.CharField(blank=True, help_text='Bank/GCash transaction reference number recorded by admin on approval.', max_length=200),
        ),
        migrations.AlterField(
            model_name='payout',
            name='period_end',
            field=models.DateField(blank=True, help_text='End of the earnings period covered by this payout.', null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='period_start',
            field=models.DateField(blank=True, help_text='Start of the earnings period covered by this payout.', null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason provided by admin when rejecting a payout request.'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved or rejected this payout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
