from django.core.management.base import BaseCommand
from pharmacy.models import Medicine


MEDICINES = [
    {"name": "amoxicillin", "generic_name": "wala ko kahibaw", "category": "medications", "price": 6.00, "description": "i huwad sa samad", "dosage_form": "500 mg", "manufacturer": "", "requires_prescription": True, "in_stock": True, "quantity": 3, "image": "https://res.cloudinary.com/drpqzldmp/image/upload/v1775396953/medicines/dup_fRUCeDe_N3wgXiC_6lpNSHD.jpg", "pharmacy_partner": "rose", "prescription_note": ""},
    {"name": "Biogesic (Paracetamol 500mg)", "generic_name": "Paracetamol", "category": "Pain Relief", "price": 5.00, "description": "Relieves mild to moderate pain and reduces fever.", "dosage_form": "Tablet", "manufacturer": "Unilab", "requires_prescription": False, "in_stock": True, "quantity": 500, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Alaxan FR (Ibuprofen + Paracetamol)", "generic_name": "Ibuprofen + Paracetamol", "category": "Pain Relief", "price": 12.00, "description": "Fast relief for pain and fever.", "dosage_form": "Tablet", "manufacturer": "Unilab", "requires_prescription": False, "in_stock": True, "quantity": 300, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Mefenamic Acid 500mg", "generic_name": "Mefenamic Acid", "category": "Pain Relief", "price": 8.50, "description": "Used for mild to moderate pain including menstrual cramps.", "dosage_form": "Capsule", "manufacturer": "Generics Pharmacy", "requires_prescription": False, "in_stock": True, "quantity": 400, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Celecoxib 200mg", "generic_name": "Celecoxib", "category": "Pain Relief", "price": 25.00, "description": "COX-2 inhibitor for arthritis and acute pain.", "dosage_form": "Capsule", "manufacturer": "Pfizer", "requires_prescription": True, "in_stock": True, "quantity": 200, "pharmacy_partner": "", "prescription_note": "Requires valid prescription. Present to pharmacist before dispensing."},
    {"name": "Tramadol 50mg", "generic_name": "Tramadol HCl", "category": "Pain Relief", "price": 18.00, "description": "Opioid analgesic for moderate to severe pain.", "dosage_form": "Capsule", "manufacturer": "Generics Pharmacy", "requires_prescription": True, "in_stock": True, "quantity": 150, "pharmacy_partner": "", "prescription_note": "Controlled substance. Valid prescription required."},
    {"name": "Azithromycin 500mg", "generic_name": "Azithromycin", "category": "Antibiotics", "price": 45.00, "description": "Macrolide antibiotic for respiratory and skin infections.", "dosage_form": "Tablet", "manufacturer": "Pfizer", "requires_prescription": True, "in_stock": True, "quantity": 200, "pharmacy_partner": "", "prescription_note": "Prescription required. Complete the full course."},
    {"name": "Ciprofloxacin 500mg", "generic_name": "Ciprofloxacin", "category": "Antibiotics", "price": 22.00, "description": "Fluoroquinolone antibiotic for urinary tract and other infections.", "dosage_form": "Tablet", "manufacturer": "Bayer", "requires_prescription": True, "in_stock": True, "quantity": 250, "pharmacy_partner": "", "prescription_note": "Prescription required."},
    {"name": "Cloxacillin 500mg", "generic_name": "Cloxacillin", "category": "Antibiotics", "price": 14.00, "description": "Penicillinase-resistant antibiotic for staphylococcal infections.", "dosage_form": "Capsule", "manufacturer": "Generics Pharmacy", "requires_prescription": True, "in_stock": True, "quantity": 300, "pharmacy_partner": "", "prescription_note": "Prescription required."},
    {"name": "Co-Amoxiclav 625mg", "generic_name": "Amoxicillin + Clavulanic Acid", "category": "Antibiotics", "price": 55.00, "description": "Combination antibiotic for resistant bacterial infections.", "dosage_form": "Tablet", "manufacturer": "GlaxoSmithKline", "requires_prescription": True, "in_stock": True, "quantity": 180, "pharmacy_partner": "", "prescription_note": "Prescription required."},
    {"name": "Doxycycline 100mg", "generic_name": "Doxycycline Hyclate", "category": "Antibiotics", "price": 16.00, "description": "Tetracycline antibiotic for respiratory, skin, and tick-borne infections.", "dosage_form": "Capsule", "manufacturer": "Generics Pharmacy", "requires_prescription": True, "in_stock": True, "quantity": 220, "pharmacy_partner": "", "prescription_note": "Prescription required."},
    {"name": "Amlodipine 5mg", "generic_name": "Amlodipine Besylate", "category": "Cardiovascular", "price": 9.00, "description": "Calcium channel blocker for hypertension and angina.", "dosage_form": "Tablet", "manufacturer": "Generics Pharmacy", "requires_prescription": True, "in_stock": True, "quantity": 400, "pharmacy_partner": "", "prescription_note": "Prescription required. Do not stop without consulting your doctor."},
    {"name": "Losartan 50mg", "generic_name": "Losartan Potassium", "category": "Cardiovascular", "price": 12.00, "description": "ARB for high blood pressure and kidney protection in diabetics.", "dosage_form": "Tablet", "manufacturer": "Merck", "requires_prescription": True, "in_stock": True, "quantity": 350, "pharmacy_partner": "", "prescription_note": "Prescription required."},
    {"name": "Metoprolol 50mg", "generic_name": "Metoprolol Tartrate", "category": "Cardiovascular", "price": 11.00, "description": "Beta-blocker for hypertension and heart failure.", "dosage_form": "Tablet", "manufacturer": "AstraZeneca", "requires_prescription": True, "in_stock": True, "quantity": 300, "pharmacy_partner": "", "prescription_note": "Prescription required."},
    {"name": "Atorvastatin 20mg", "generic_name": "Atorvastatin Calcium", "category": "Cardiovascular", "price": 28.00, "description": "Statin for lowering cholesterol and reducing cardiovascular risk.", "dosage_form": "Tablet", "manufacturer": "Pfizer", "requires_prescription": True, "in_stock": True, "quantity": 250, "pharmacy_partner": "", "prescription_note": "Prescription required."},
    {"name": "Aspirin 80mg (Enteric-coated)", "generic_name": "Acetylsalicylic Acid", "category": "Cardiovascular", "price": 4.50, "description": "Low-dose aspirin for antiplatelet therapy and heart attack prevention.", "dosage_form": "Tablet", "manufacturer": "Bayer", "requires_prescription": False, "in_stock": True, "quantity": 500, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Vitamin C 500mg", "generic_name": "Ascorbic Acid", "category": "Vitamins", "price": 5.00, "description": "Antioxidant vitamin that supports immune function.", "dosage_form": "Tablet", "manufacturer": "Unilab", "requires_prescription": False, "in_stock": True, "quantity": 800, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Vitamin D3 1000IU", "generic_name": "Cholecalciferol", "category": "Vitamins", "price": 15.00, "description": "Supports bone health and immune system.", "dosage_form": "Softgel Capsule", "manufacturer": "Generics Pharmacy", "requires_prescription": False, "in_stock": True, "quantity": 600, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Zinc 20mg", "generic_name": "Zinc Sulfate", "category": "Vitamins", "price": 8.00, "description": "Essential mineral for immune function and wound healing.", "dosage_form": "Tablet", "manufacturer": "Unilab", "requires_prescription": False, "in_stock": True, "quantity": 500, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Centrum Multivitamins + Minerals", "generic_name": "Multivitamins + Minerals", "category": "Vitamins", "price": 22.00, "description": "Complete daily multivitamin for adults.", "dosage_form": "Tablet", "manufacturer": "Pfizer", "requires_prescription": False, "in_stock": True, "quantity": 400, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Folic Acid 400mcg", "generic_name": "Folic Acid", "category": "Vitamins", "price": 4.00, "description": "B-vitamin essential for cell growth and prenatal health.", "dosage_form": "Tablet", "manufacturer": "Generics Pharmacy", "requires_prescription": False, "in_stock": True, "quantity": 700, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Vitamin B Complex", "generic_name": "Thiamine + Riboflavin + Niacin + B6 + B12", "category": "Vitamins", "price": 7.00, "description": "Supports energy metabolism and nervous system health.", "dosage_form": "Tablet", "manufacturer": "Unilab", "requires_prescription": False, "in_stock": True, "quantity": 600, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Betadine Solution 60ml", "generic_name": "Povidone-Iodine", "category": "First Aid", "price": 85.00, "description": "Antiseptic solution for wound cleaning and disinfection.", "dosage_form": "Solution", "manufacturer": "Mundipharma", "requires_prescription": False, "in_stock": True, "quantity": 200, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Hydrogen Peroxide 3% 120ml", "generic_name": "Hydrogen Peroxide", "category": "First Aid", "price": 35.00, "description": "Mild antiseptic for minor cuts and abrasions.", "dosage_form": "Solution", "manufacturer": "Generics Pharmacy", "requires_prescription": False, "in_stock": True, "quantity": 250, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Hydrocortisone Cream 1%", "generic_name": "Hydrocortisone", "category": "First Aid", "price": 55.00, "description": "Topical corticosteroid for itching, rashes, and minor skin irritations.", "dosage_form": "Cream", "manufacturer": "Generics Pharmacy", "requires_prescription": False, "in_stock": True, "quantity": 180, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Oral Rehydration Salts (Hydrite)", "generic_name": "ORS (Sodium + Glucose)", "category": "First Aid", "price": 12.00, "description": "Replaces fluids and electrolytes lost during diarrhea or vomiting.", "dosage_form": "Powder for Solution", "manufacturer": "Unilab", "requires_prescription": False, "in_stock": True, "quantity": 400, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Cetirizine 10mg", "generic_name": "Cetirizine HCl", "category": "First Aid", "price": 7.00, "description": "Non-drowsy antihistamine for allergies, hives, and hay fever.", "dosage_form": "Tablet", "manufacturer": "Generics Pharmacy", "requires_prescription": False, "in_stock": True, "quantity": 500, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Loperamide 2mg", "generic_name": "Loperamide HCl", "category": "First Aid", "price": 6.00, "description": "Anti-diarrheal for acute and traveler's diarrhea.", "dosage_form": "Capsule", "manufacturer": "Unilab", "requires_prescription": False, "in_stock": True, "quantity": 450, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Metformin 500mg", "generic_name": "Metformin HCl", "category": "Maintenance", "price": 6.50, "description": "First-line oral medication for type 2 diabetes.", "dosage_form": "Tablet", "manufacturer": "Generics Pharmacy", "requires_prescription": True, "in_stock": True, "quantity": 500, "pharmacy_partner": "", "prescription_note": "Prescription required."},
    {"name": "Glimepiride 2mg", "generic_name": "Glimepiride", "category": "Maintenance", "price": 18.00, "description": "Sulfonylurea for blood sugar control in type 2 diabetes.", "dosage_form": "Tablet", "manufacturer": "Sanofi", "requires_prescription": True, "in_stock": True, "quantity": 300, "pharmacy_partner": "", "prescription_note": "Prescription required."},
    {"name": "Omeprazole 20mg", "generic_name": "Omeprazole", "category": "Maintenance", "price": 10.00, "description": "Proton pump inhibitor for acid reflux and peptic ulcers.", "dosage_form": "Capsule", "manufacturer": "Generics Pharmacy", "requires_prescription": False, "in_stock": True, "quantity": 450, "pharmacy_partner": "", "prescription_note": ""},
    {"name": "Levothyroxine 50mcg", "generic_name": "Levothyroxine Sodium", "category": "Maintenance", "price": 14.00, "description": "Thyroid hormone replacement for hypothyroidism.", "dosage_form": "Tablet", "manufacturer": "Abbott", "requires_prescription": True, "in_stock": True, "quantity": 300, "pharmacy_partner": "", "prescription_note": "Prescription required."},
    {"name": "Salbutamol 2mg", "generic_name": "Salbutamol Sulfate", "category": "Maintenance", "price": 5.50, "description": "Bronchodilator for asthma and COPD maintenance.", "dosage_form": "Tablet", "manufacturer": "Generics Pharmacy", "requires_prescription": True, "in_stock": True, "quantity": 350, "pharmacy_partner": "", "prescription_note": "Prescription required."},
    {"name": "Amlodipine 10mg", "generic_name": "Amlodipine Besylate", "category": "Maintenance", "price": 12.00, "description": "Higher-dose calcium channel blocker for uncontrolled hypertension.", "dosage_form": "Tablet", "manufacturer": "Generics Pharmacy", "requires_prescription": True, "in_stock": True, "quantity": 300, "pharmacy_partner": "", "prescription_note": "Prescription required."},
    {"name": "Losartan 100mg", "generic_name": "Losartan Potassium", "category": "Maintenance", "price": 18.00, "description": "Higher-dose ARB for hypertension.", "dosage_form": "Tablet", "manufacturer": "Merck", "requires_prescription": True, "in_stock": True, "quantity": 250, "pharmacy_partner": "", "prescription_note": "Prescription required."},
]


class Command(BaseCommand):
    help = "Seed medicines into the database"

    def handle(self, *args, **kwargs):
        created = 0
        skipped = 0
        for data in MEDICINES:
            image = data.pop("image", None)
            obj, is_new = Medicine.objects.get_or_create(name=data["name"], defaults=data)
            if is_new:
                if image:
                    obj.image = image
                    obj.save()
                created += 1
            else:
                skipped += 1

        self.stdout.write(self.style.SUCCESS(f"Done: {created} created, {skipped} skipped (already exist)."))
